// Lightweight design tokens and style helpers for consistent inline styling

export const theme = {
  color: {
    bg: '#ffffff',
    surface: '#f9fafb',
    panel: '#f3f4f6',
    text: '#111827',
    muted: '#6b7280',
    border: '#e5e7eb',
    brand: '#111827',
    accent: '#2563eb',
  },
  radius: {
    sm: 6,
    md: 10,
    lg: 14,
  },
  shadow: {
    sm: '0 1px 2px rgba(0,0,0,0.05)',
    md: '0 4px 10px rgba(0,0,0,0.06)',
    lg: '0 8px 24px rgba(0,0,0,0.08)'
  },
  space: (n: number) => `${n * 4}px`,
} as const;

export const styles = {
  container: {
    maxWidth: 1200,
    margin: '0 auto',
    padding: '0.75rem 1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    flexWrap: 'wrap' as const,
  },
  brandLink: {
    color: theme.color.brand,
    textDecoration: 'none',
    fontWeight: 700,
    fontSize: '1rem',
    letterSpacing: 0.2,
  },
  buttonBase: {
    padding: '0.45rem 0.8rem',
    border: `1px solid ${theme.color.border}`,
    background: theme.color.bg,
    borderRadius: theme.radius.sm,
    cursor: 'pointer',
    textDecoration: 'none',
    color: theme.color.text,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  },
  buttonPrimary: {
    background: theme.color.accent,
    color: '#fff',
    border: '1px solid transparent',
  },
  buttonGhost: {
    background: theme.color.bg,
    color: theme.color.text,
    border: `1px solid ${theme.color.border}`,
  },
  chip: {
    padding: '2px 8px',
    background: theme.color.panel,
    borderRadius: 999,
    fontSize: 12,
    color: theme.color.muted,
  },
  card: {
    border: `1px solid ${theme.color.border}`,
    background: theme.color.bg,
    borderRadius: theme.radius.md,
    boxShadow: theme.shadow.sm,
  },
  elevated: {
    border: `1px solid ${theme.color.border}`,
    background: `linear-gradient(180deg, #fff, ${theme.color.surface})`,
    borderRadius: theme.radius.lg,
    boxShadow: theme.shadow.md,
  },
  tableWrap: {
    ...({} as any),
    border: `1px solid ${theme.color.border}`,
    background: theme.color.bg,
    borderRadius: theme.radius.lg,
    boxShadow: theme.shadow.sm,
    overflow: 'hidden',
  },
  tableHeader: {
    display: 'grid',
    gridTemplateColumns: 'minmax(200px,1fr) 120px 180px 120px',
    alignItems: 'center',
    gap: 8,
    padding: '12px 16px',
    background: 'linear-gradient(180deg, #fbfbfd, #f4f6f8)',
    color: theme.color.muted,
    fontSize: 12,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.6,
    borderBottom: `1px solid ${theme.color.border}`,
  },
  tableRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(200px,1fr) 120px 180px 120px',
    alignItems: 'center',
    gap: 8,
    padding: '12px 16px',
    borderBottom: `1px solid ${theme.color.border}`,
  },
  tableIconAndName: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
  },
  srOnly: {
    position: 'absolute' as const,
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap' as const,
    border: 0,
  },
};
